### ISSUE TITLE
Latte pro breaking the free version

### ISSUE THREAD

**Issue by Creeperface01** [mesour-intellij-plugins/latte-pro-issues#124]
Would it be possible to stop breaking the free version of the plugin? I appreciate the work on the pro version which brings latte plugin to the next level and I pay for it. However the free version "somehow" worked until the pro version has been released. Now it seems to me that often there are breaking bugs which prevent using the plugin. I suppose I'm donating the development not only of the pro version but also to at least somehow maintain the free one to be usable for other users. I hope it would be possible to achieve for future releases, otherwise this looks a bit like forcing the users to buy pro version by breaking the free one.

Is there any official issue tracker of the free version? The github repository does not seem to be active.

Thanks

**Comment by mesour** [comment]
I'm glad that I now have the time to upgrade the paid version. It would be ideal if a contributor could get involved in the development of the free plugins so that it doesn't all rely on me. Unfortunately, so far, no one willing to dedicate their time to it has been found. The Latte free plugin is essentially "unmaintainable," so I plan to downgrade it to just a syntax highlighter (back to the state before I started working on it). Then, it should be stable, and there shouldn't be a problem using it.

Issue tracker for free plugin is here: https://github.com/nette-intellij/intellij-latte/issues
