### ISSUE TITLE
Will it be finally maintained?

### ISSUE THREAD

**Issue by Tommasv** [mesour-intellij-plugins/latte-pro-issues#174]
**Message**
I would like to raise a question about the current state of support for this plugin. I have noticed a long term absence of any feedback, bug fixes or new updates, which gives me the impression that the development and maintenance of the plugin is focused on generating revenue rather than actually developing and improving the product. The plugin is quite expensive, while constantly encountering bugs that greatly affect its usability. In particular, working in Latte puts a disproportionate load on the processor, leading to situations where users are literally "heating food on their laptop".

Many users would certainly appreciate it if the developer started to focus more on the plugin, especially considering the high costs associated with its acquisition, whether for individuals or companies. It is indeed frustrating to spend significant amounts of money annually on a plugin that has significant deficiencies, with no answers to reported problems. I firmly believe that the author of the plugin will take these suggestions into account and start responding more effectively to the needs of the user community.

Thank you and I expect an improved approach.

Sincerely,
your "satisfied user"

**Environment:**
 - PhpStorm version PhpStorm 2024.2.1
 - Plugin version 1.2.1

**Comment by mesour** [comment]
@Tommasv you're exaggerating, and there are certain things I won't comment on at all.

It's important to note that for the majority of users, it works just fine. Performance issues don't have an easy fix, and I started working on them at the beginning of the year. The proposed adjustments turned out to be ineffective, so I had to rethink everything. I spent the summer reflecting on it, and now I have a potential solution that might work. Sometimes, it just takes time. If you need more detailed information regarding development, try Slack [péhápkaři](https://pehapkari.cz/?ref=codebldr), where there are channels for IntelliJ plugins.

Last year, I fixed most of the bugs that were bothering people, and since then, no critical issues have emerged. A small update will be released in the coming weeks, and after that, I'll focus on improving performance. But it's not about releasing a performance improvement update every month; we're talking about Latte v2.0 here.

So, don't worry, development is ongoing.
