### ISSUE TITLE
Latte file icon is broken with light theme

### ISSUE THREAD

**Issue by kolinger** [mesour-intellij-plugins/latte-pro-issues#96]
**Describe the bug**
Latte file icon in project files (and everywhere else) is broken with light IDE theme.

**Environment:**
 - PhpStorm version: 2022.3.3
 - Plugin version: 1.0.10

**To Reproduce**
1. Set **light** PhpStorm theme
2. Install plugin
3. Create .latte file
4. Look at icon of created .latte file in project files or at icon in tab of opened .latte file

**Code**
Not applicable.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/1590930/224800804-f2b83e88-a74d-425e-bd9f-00833730a61c.png)

**Additional context**
Icon is fine with dark theme.
This bug is not present in 1.0.8.

**Comment by elcheco** [comment]
I have the same issue in the latest version 2023.2 and the dark theme and Latte Pro 1.0.11.
I have parallelly installed 2023.1.4 and the same version Latte Pro 1.0.11 and in this version icon works fine.

I have also noticed that classes autocomplete through `varType` or `templateType` doesn't work in 2023.2 but in version 2023.1.4 it works fine...

**Comment by elcheco** [comment]
@mesour 

I wonder When the autocompletion will work in the latest 2023.2 version? I can survive missing icons, but not autocompletion. I would accept that these issues for some time around the release of the new version, but it was more than two weeks ago.

I work for the company, and I ordered 5 business licenses of this plugin. It's just a template system, and it's more expensive than, for example, Laravel Idea, but there's no support for the money...

I am the one who needs to listen to complaints from other developers who have experiences with Symfony's Twig or Laravel's Blade that Latte's plugin is not working.

**Comment by mesour** [comment]
@elcheco TIP: if you find bug, please create issue. This issue is about icons and you write about another more important bug. If you create new issue, I will read it immediately. But if you make a comment with info that is not related to the issue, I can ignore it for some time.

---

You can't compare Symfony or Laravel to Nette just in terms of community size. How many people are working on their plugin? Does the framework community care about the plugin? These are important differences. Nette plugins are not supported by Nette. People around Nette are only promoting my plugins because there are no others. If Symfony or Laravel is that much better for you, you can use that instead of Nette.

Developing plugins is a long-term job, when I created them I had more time. I'm dealing with family stuff now and just don't have time for it, so it's a miracle I even get around to any updates once in a while.

As a workaround, you can do not update PhpStorm to the latest version right away, but wait until the plugins are updated as well. It's not the best solution, but currently the only one that will prevent potential problems.
